compressionLevel: 0

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableImmutableInstalls: false

enableInlineBuilds: true

enableProgressBars: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"
